name: house-price-prediction
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - joblib
  - pip:
      - fastapi
      - "uvicorn[standard]"
      - python-multipart
      - pytest
      - httpx
